/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArtText: typeof import('./src/components/ArtText/index.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Fish: typeof import('./src/components/Fish/index.vue')['default']
    Foot: typeof import('./src/components/Foot/index.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    NotesDetail: typeof import('./src/components/NotesDetail/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Swiper: typeof import('./src/components/TravelDetail/swiper.vue')['default']
    TravelDetail: typeof import('./src/components/TravelDetail/index.vue')['default']
  }
}
